version: '2.2'

services:
  test:
    image: bgrande/swooletest
    cpus: '1'
    mem_limit: 128M
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      EXPOSE_HOSTNAME: 0.0.0.0
      PHP_XDEBUG_ENABLED: 0
    volumes:
      - $PWD:/var/www
